import ToastProvider from "@/components/Toast";
import type { Metadata } from "next";
import { Gabarito, Imbue } from "next/font/google";
import "./globals.css";

const gabarito = Gabarito({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-sans",
});

const imbue = Imbue({
  weight: "800",
  subsets: ["latin"],
  style: ["normal"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-zinc-950 antialiased ${gabarito.variable} ${imbue.variable} relative font-sans`}
      >
        <ToastProvider>{children}</ToastProvider>

        <svg className="pointer-events-none absolute left-0 top-0 -z-10 h-full w-full opacity-10">
          <filter id="delbadeoliveiraisalegend">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.80"
              numOctaves="4"
              stitchTiles="stitch"
            />
          </filter>
          <rect
            width="100%"
            height="100%"
            filter="url(#delbadeoliveiraisalegend)"
          />
        </svg>
      </body>
    </html>
  );
}
