import ToastProvider from "@/components/Toast";
import type { Metadata } from "next";
import { Gabarito, Imbue } from "next/font/google";
import "./globals.css";

const gabarito = Gabarito({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-sans",
});

const imbue = Imbue({
  weight: "800",
  subsets: ["latin"],
  style: ["normal"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-zinc-950 antialiased ${gabarito.variable} ${imbue.variable} font-sans`}
      >
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
